services:
  engine:
    build: ./engine
    container_name: engine
    restart: unless-stopped
  app:
    build: .
    container_name: app
    restart: unless-stopped
    links:
      - db:db
      - engine:engine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chess.rule=Host(`chess.ahop.dev`)"
      - "traefik.http.routers.chess.entrypoints=websecure"
      - "traefik.http.routers.chess.tls.certresolver=myresolver"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
